"""Constants for joint angle indices used in pose feature extraction."""

LEFT_ELBOW_ANGLE_IDX = 0
RIGHT_ELBOW_ANGLE_IDX = 1
LEFT_SHOULDER_ANGLE_IDX = 2
RIGHT_SHOULDER_ANGLE_IDX = 3
LEFT_BODY_ANGLE_IDX = 4
RIGHT_BODY_ANGLE_IDX = 5
